# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Test'
          script:
            - git push https://heroku:d998e6ff-b040-405a-a255-5ce5547b3107@git.heroku.com/mernskill.git HEAD
    
